[package]
name = "file-extension-fixer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fixFileExt"
path = "./src/main.rs"

[profile.release]
strip = true
lto = true

[dependencies]
indicatif = "0.17.11"
infer = { version = "0.19.0", default-features = false }
num-format = "0.4.4"
